services:

  church_finance_redis:
    image: redis:latest
    container_name: church_finance_redis
    ports:
      - "6377:6379"
    command: [ "redis-server" ]
    networks:
      - church_sion

  church_finance_api:
    container_name: church_finance_api
    image: church_finance_api
    restart: always
    build:
      context: .
    command: npm run dev
    environment:
      NODE_ENV: local

      MONGO_PASS: Ljm5aB8h7vOTeDeA
      MONGO_USER: user_sion
      MONGO_DB: dbsionfinancial
      MONGO_SERVER: freesionfinancial.cmomlts.mongodb.net

      JWT_SECRET: MG9hNm4xdTFlbGJ6c2a10N7trhjhBwEYj9l7VGDT9e5sc2s4WnEwY2I0dEROeS1uVC1Nd2Rhe7rWG3rfWXX

      BUCKET_FILES: churchs3

      REDIS_HOST: church_finance_redis
      REDIS_PORT: 6379
      GOOGLE_APPLICATION_CREDENTIALS: /credentials.json


    volumes:
      - ./:/app
      - /app/node_modules
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/credentials.json
    ports:
      - "5200:8080"
    networks:
      - church_sion
    depends_on:
      - church_finance_redis

networks:
  church_sion:
    driver: bridge
